language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - mvn verify -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn coveralls:report
notifications:
  email: false
